SYS-4404 Added systemd service support for all values.
k0ste/ansible-role-openvpn-ldap pull request #1
Opened 2021-10-29 04:24 UTC by firemdkfighter

2021-10-29 06:42 UTC, k0ste requested changes

2021-10-29 06:42 UTC, k0ste commented on templates/openvpn_service.j2
> +{{ 'Restart=' ~ s.restart }}
Operator should be `+` for string

2021-10-29 06:42 UTC, k0ste commented on README.md
> +  - restart: 'always'
Documentation should be updated accordingly changes

2021-10-29 06:51 UTC, firemdkfighter commented on templates/openvpn_service.j2
> +{{ 'Restart=' ~ s.restart }}
You have the same operator above and below. https://github.com/k0ste/ansible-role-openvpn-ldap/blob/master/templates/openvpn_service.j2#L12

2021-10-29 06:54 UTC, firemdkfighter commented on README.md
> +  - restart: 'always'
Updated.

2021-10-29 07:44 UTC, k0ste commented on templates/openvpn_service.j2
> +{{ 'Restart=' ~ s.restart }}
Right! Because is may be `int` and should be explicitly convert to `str` before concatenation with string

2021-11-01 05:25 UTC, k0ste commented
Thanks

2021-11-01 05:25 UTC, merged